export const error: string;
export const textCenter: string;
export const textLeft: string;
export const textRight: string;
export const txtCerulean: string;
export const txtLemon: string;
export const txtOrange: string;
export const txtRed: string;
export const txtRegal: string;
