development:
  SECRET_KEY: 'E6D5E1G8Q4E69R4CE6D5E1G8Q4E69R4C'
  BASE_URL: 'http://localhost:3000'
  DATABASE_USERNAME: 'alextang'
  DATABASE_PASSWORD: 'Alex@1030'
  DATABASE_HOST: 'localhost'
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  GOOGLE_STORAGE_ID: 'GOOGQFXQPXS2H5TEY663APPR'
  GOOGLE_STORAGE_SECRET: 'zhJp2b4PbnK+xiBC+d8KMj5nDGbOi9UqJW1aK6uQ'
  GOOGLE_STORAGE_BUCKET: 'mms-upload-dev'
production:
  SECRET_KEY: 'E6D5E1G8Q4E69R4CE6D5E1G8Q4E69R4C'
  BASE_URL: 'https://igneous-ethos-273113.appspot.com'
  DATABASE_USERNAME: 'postgres'
  DATABASE_PASSWORD: 'Alex@1030'
  DATABASE_HOST: '10.84.32.3'
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  GOOGLE_STORAGE_ID: 'GOOGQFXQPXS2H5TEY663APPR'
  GOOGLE_STORAGE_SECRET: 'zhJp2b4PbnK+xiBC+d8KMj5nDGbOi9UqJW1aK6uQ'
  GOOGLE_STORAGE_BUCKET: 'mms-upload-images'
test:
  SECRET_KEY: 'E6D5E1G8Q4E69R4CE6D5E1G8Q4E69R4C'
  BASE_URL: 'http://localhost:3000'
  DATABASE_USERNAME: 'alextang'
  DATABASE_PASSWORD: 'Alex@1030'
  DATABASE_HOST: 'localhost'
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  GOOGLE_STORAGE_ID: 'GOOGQFXQPXS2H5TEY663APPR'
  GOOGLE_STORAGE_SECRET: 'zhJp2b4PbnK+xiBC+d8KMj5nDGbOi9UqJW1aK6uQ'
  GOOGLE_STORAGE_BUCKET: 'mms-upload-dev'